### ISSUE TITLE
Switch to a more span-friendly grid API

### ISSUE THREAD

**Issue by ab5tract** [ab5tract/Terminal-Print#15]
In the comments of PR #12 , I mentioned that I was looking into some lower-level options for performance enhancement:

> BTW, I'm hoping to have some time soon to look into writing some lower level functions in C that
> could help make some speed improvements as well.
> - ab5tract

japhb responded:

> Actually, before doing that, I think there may be advantage to making an
> algorithmic improvement for cases of printing a lot of text (or drawing
> rectangles or similar shapes) -- switching from a column-major to a
> row-major representation in the grid, and taking advantage of available
> speedups when rendering horizontal spans of text with the same color (no
> need to move the cursor to every cell individually and color each cell
> individually, just move to the start of the span and set the color once
> for the entire span, and then print a line of text trimmed to the screen
> edge).
> 
> To really make use of the available performance gains, this would
> require more cleverness in the span handling ... but changing the layout
> to be row-major can be done _now_ and get modest performance
> improvements, while leaving the option of adding cleverness later
> without another API break.
> - japhb

I think this is a great idea, with a single caveat: I want `.print-string` and `T()` and the like to all remain column-major. My reasoning for not going with row-major in the first place was to provide the less confusing means of coordination, but I think that we can reasonably switch the `@.grid` array itself over to row-major without suffering any serious fallout.

This way people can choose to use the more familiar-feeling column-major coordinates via the `.print` API or juggle the `Cell` objects themselves while working directly in row-major coordinates via `@.grid`.

I'm also open to discussing further span-related niceties, because I think that it fits within the problem domain of `Terminal::Print`. Not to mention that it would be nice to make higher level abstractions like UI library less of a pain to implement.

**Comment by japhb** [comment]
I've sent a pull request (#16) that ends with the very beginnings of my thoughts on span-wise APIs for T::P::Grid, to see if it seems sane to you (as a bonus, there are also a couple big speedups in there too).

In the mean time, I realized it's a bad idea to design a lot of API without having actual use cases in hand, so I've been working on an example program that will exercise some of these requirements.  You can see the very beginnings of this in [my ui_test branch](https://github.com/japhb/Terminal-Print/blob/ui_test/examples/rpg-ui.p6).  Once that's more fleshed out, I'll have a decent idea what I actually need from the API.

**Comment by ab5tract** [comment]
I think the RPG case makes a really nice test bed. For example, the progress bar. I'd like for this to have a really simple semantics out of the box.

It might be the progress bar example, but I'm currently imagining a `.print-string` target (or perhaps a more specialized `.print-span`) that takes a (sub-class of ?) `Supply` as well as some optional sizing and starting coordinates.

This way you could imagine spans which are more or less in charge of printing themselves. The code block passed to `$span-supply.act` could have some standardized arguments. It would also allow spans to have relative coordinate systems (starting again from 0,0 within their bounding box).

**Comment by japhb** [comment]
I've made a little more progress in the ui_test branch, but still lots more to go.  I've converted the Grid methods that I've made so far to use x-before-y coordinates; you were right, that's more consistent and clear.

I'm also starting to build a Widget abstraction in the rpg-ui.p6 code in order to use relative coordinates, though that conversion is still in progress.

Finally, I've made some visual improvements, and added an --ascii flag to rpg-ui.p6 to switch between ASCII and full-Unicode drawing modes; so far this mostly affects border drawing and the rendering of the title.

Word of war

**Comment by japhb** [comment]
And now a bit more, with more complete character display, early map display, and a crash fix in the span routines.

**Comment by ab5tract** [comment]
Finally had a proper moment to check out the `ui_test`. I must say, I really like what I see when running `examples/rpg-ui.p6`. I've only given a precursory glance at the code, but my first impression is: looks like we need to create a `Terminal::Input` sooner rather than later!

Nice work, @japhb!

**Comment by japhb** [comment]
You're right that we'll need a Terminal::Input soon.  :-)

I've added initial support for 256-color mode when --color-bits=8 is set (available using [my fork of Terminal::ANSIColor](https://github.com/japhb/Terminal-ANSIColor); [pull request](https://github.com/tadzik/Terminal-ANSIColor/pull/6) to tadzik's upstream pending).  It's used to show a light source glow around the party, and to dim the background grid in the map viewer.  I also have party movement and automatic map panning.

Finally, I added an internal performance measurement framework to rpg-ui, and when in --bench mode the summary results are displayed at program exit.

**Comment by japhb** [comment]
And now more performance improvements, plus tadzik++ merged my initial PR to Terminal::ANSIColor.  Still more to do, of course, but it's looking better.

**Comment by ab5tract** [comment]
Thanks for the continued efforts, @japhb !

One thing that came to mind when looking briefly at the `rpg-ui` code is that something like your intro splash screen would really benefit from having multiple grids and screen blitting (re)implemented.

This way you could really start drawing your next grid in another thread while the progress bar is ticking away.

``````````````
my $progress-supplier = Supplier.new;
my $progress-supply = $progress-supplier.Supply;
T.add-grid('main');
my $done-main = start {
    # do setup
    $progress-supply.emit(10); # finished 10 percent of the work
   # do 25% more setup
   $progress-supply.emit(25);
};

my $progress-bar = ProgressBar.new(T.grid, $x, $y);
$progress-supply.act(-> $pct { $progress-bar.progress( $pct ) });

await $done-main.then({ T.blit('main') });
``````````````

Hopefully this week I will have a chance to poke some more, but hopefully that gives you a bit of an idea of what I mean about the potential for multiple screens/blitting.

And again, thank you so much for all your contributions already! You've been very helpful in maturing this library and I really appreciate it.

**Comment by japhb** [comment]
You're quite welcome!

Hmmm, that looks like a good idea, yeah.  I can work on that on my next hacking cycle, but those tend to be a little sporadic -- would you like me to merge my ui_test branch back to master and PR it, so you can hack on the most recent version?

**Comment by ab5tract** [comment]
I've got a branch which is tracking yours. Let's keep poking at it in the
branch until it feels 100%. My hacking cycles are also sporadic these days,
so this way we can ensure we have the best-possible solutions for this
slightly higher level stuff before it goes into master.

**Comment by japhb** [comment]
Ah, didn't realize you were tracking ui_test as well.  Looks like yours is trailing a bit, though.

Anyway, that plan sounds fine with me; I'll keep working in the branch.

**Comment by japhb** [comment]
So quite a bundle more changes in ui_test, among them:

- Thread safe timing code, Widget, and ProgressBar
- Better offscreen drawing capabilities
- Widgets can have parents
- Bitrot fixes and a new switch-grid method in Terminal::Print itself
- Build game state and UI in separate thread
- Animated title that changes while game and UI are being built (and ProgressBar updated)
- Lots of refactoring to put code and state where it belongs
- Various other minor fixes

At this point what I'd really like is to be able to use the new 'submethod TWEAK', recently added to the OO model.  Any objection to switching to that once it's in released Rakudo?

**Comment by ab5tract** [comment]
Wow! This is great stuff indeed! After I have a chance to look at it a bit deeper I think we are ready merge.

Regarding TWEAK, is that just like BUILD but you already have your object initialized according to defaults beforehand? I don't object to it at all, though it piques my curiosity in terms of how you plan to use it.

Hopefully back with a more in depth reply soon.

**Comment by japhb** [comment]
There's definitely more to do and to flesh out, but it's not a super big deal which branch it's happening in.

Yes, you basically have the idea of TWEAK.  There's a few places in the code where it would be way cleaner to use TWEAK to post-process the results of new/BUILD than the hacks I put in place.  ProgressBar.init is a perfect example.  I have to make sure it's been called before anything that might need the initialized state, so I've got checks in each other method, plus I need to make sure it doesn't run twice, so I have to check for that in init itself, ... it's just ugliness that doesn't need to be there.

Can't wait for the "more in depth reply".  :-)

**Comment by japhb** [comment]
Another significant push; I'll save the pitch and just say "Time to look again."  :-)

Most significant lib change: grid-to-grid copies are properly clipped to the edges of the destination grid.

**Comment by ab5tract** [comment]
Okay, so now we *really* need to get the input side of things working, because I am ready to play some Ruins of Aktaria!

Seriously, though, I want to express my gratitude for all the work you have done in pushing this module forward. I think we are just about ready to merge this into trunk, including `Widget`!

The only change I feel slightly strong about at this point would be to change all subroutine arguments that are optional or have a default value to be named arguments instead. This would fit a bit better with the some of the pre-existing code.

This would change method calls, for instance, from `$widget.composite(True)` to `$widget.composite :print`. I definitely prefer the clarity of the latter! 

Looking at the code, this shift to named parameters would have the largest impact on the 'color' arguments across the print-string/span-string pipeline. I did find the `$color = Empty` approach pretty cool, as that then doesn't propagate into the `$!current-grid.print-string` call by default.

We could take care of this with explicit `multi` candidates where `:$color!` is defined. If no color is defined, we don't technically need to create any `Cell` objects because we could get by with just a character in that index of `@!grid`. I think this could even have the additional benefit of allowing us to optimize the color-specific code path to use the minimum number of extra `Cell` objects/escape sequences.

That minor stylistic nit aside, I love the improvements you have made!

**Comment by japhb** [comment]
Glad to hear it's starting to look good enough to want to play, I was hoping I was getting close.  :-)

You are quite welcome for the work.  It's been fun, and scratches an itch (fills a need) for me too.

Regarding having input working, I was looking around at what we have available.  Term::termios seems pretty dang low level; it seems like we'd even need to implement non-ASCII input by hand, let alone something as complicated as switching between single-key inputs and readline-like inputs.  Conversely it's not clear that the readline-like libraries have a decent single-key mode.  And I'm not at all clear on how this interacts with MoarVM async I/O.  Moreover that doesn't even begin to address terminal mouse input ... clearly more research needed on this one.

As for the named argument change, that's actually been on my todo list for a while (along with some other general code quality improvements that are bothering me), it just hadn't risen to the top quite yet.  I'll shortlist it.

I had originally planned to implement Span as a replacement for (or maybe addition to) Cell, which would allow simpler computation of minimal escape sequences and probably also reduce memory footprint ... but I'd kept with the simpler Cell-centric guts so far because I was spending my "mental complexity budget" on other things.  I don't think I'm quite ready to write that chunk of code, but it was very much my intention that having a span-centric API _now_ would allow changes in the guts later without breaking users -- plus it's just plain more efficient for many operations.

**Comment by japhb** [comment]
Another 28 commits.  This time no visual effect on rpg-ui; just a bunch of code health commits and miscellaneous fixes.  Looking better from your point of view?

**Comment by ab5tract** [comment]
Just logged in to clarify that I didn't mean to suggest we need to perform all the color/span related optimizations. And find 28 more commits! 👍 

Your points about input are well taken. It will prove challenging indeed.

As to the current state of things, this is all looking really good! There are a few things still sticking out to me, though:

## Multi method span interface

We have generally taken a multi method approach, but the span API is fragmented across several methods. These methods also tend to have different signatures `(x1, x2, ...)` vs `(x, y, ...)`. I don't feel strongly that these ought to be removed, but I do hope we can find a way to provide an _ur-method_ that wraps all of this. `(x1, x2,...)` could be `($x where *.elems == 2, ...)` or `(..., :$length)` or something even better.

What do you think? Is this feasible?

## Widget

All that needs to be done here is to a) put it into its own file (`lib/Terminal/Print/Widget.pm` seems appropriate); and b) normalize it with `Grid` in terms of `w/h` versus `columns/rows`. I like `w/h` and it matches the golfy impulses in `Terminal::Print`. But I have tried to balance the golfiness with more explicit forms.

Should we migrate `Grid` to `width/height` and then provide `.w` and `.h` accessors? Alternatively we can keep `columns/rows` and just map `.w` and `.h` to those?

Curious to hear your thoughts.

**Comment by japhb** [comment]
Multi-method span interface:  Yep, should be doable.  I was dubious until this morning when I realized the following mapping could work:

- span(Int, Int, Int) : span-string(x1, x2, y)
- span(Int, Int, Str) : set-span-text(x, y, text)
- span(Int, Int, Int, Str) : set-span-color(x1, x2, y, color)
- span(Int, Int, Str, Str) : set-span(x, y, text, color)

Is that the kind of thing you're thinking of?

As for Widget, putting it in its own file is no problem. I certainly favor using $!w and $!h in the core code (thanks for considering the change!), but I'm fine with leaving .width/.height and .columns/.rows as compatibility accessors as well.  Sound good?

Another item: something was bothering me about Widget -- unexplored use cases -- so I started working on some asynchronous animations with child widgets.  I found the current handling of child widgets racy when concurrency starts to rise; with a half dozen child widgets I would start to get occasional glitches as some children were partway into the *next* repaint cycle when the parent widget was trying to composite them into its own current repaint.  Thus even though the composite operation itself was concurrency-safe from the point of view of not corrupting the destination grid, it might pull data from the source (child) grid before the source grid was completely ready if the overall repaint had been triggered by a *different* child.  I'm letting my brain ruminate on this problem a bit, because my initial solution would be guaranteed to work without races, but would involve rather heavy GC load.  It's hard to find a solution that won't race, won't do a lot of wasted work, parallelizes well, and is kind to the GC, all at once.

**Comment by ab5tract** [comment]
I was thinking something more like `method span($x, $y, :$w, :$text, :$color, :$print)`. With this signature `$x2` becomes unnecessary as the same information is provided via `:$w`, which is itself optional because it will take the width of `:$text` by default.

After starting this comment it occurred to me that creating multi method candidates would be annoying and it makes rather more sense in this case to simply integrate the optional named params as they are specified (or not).

Regarding `Widget` and async, I wonder whether using something like `OO::Actors` would come in handy here. It depends on whether this would actually help: "Methods are run in the thread pool, one call at a time." [OO::Actors](https://github.com/jnthn/oo-actors)

If I understand this correctly, this class of problems should be resolved since the update operation and the draw operation could not be in contention If the performance of `OO::Actors` is anything like `OO::Monitors`, it will perform much better than anything we roll ourselves.

And if it does not resolve it by itself, I wonder if combining it with a supply that emits widgets into the `react` one at a time would work?

**Comment by ab5tract** [comment]
With some potential defaults defaults: `method span($x, $y, :$w = 1, :$text = '', :$color, :$print = False)`

**Comment by japhb** [comment]
Hmmm, I see where you're going with the span method with named args ... but do you want to change the general T::P (or at least T::P::Grid) API to be like that?  Right now it's more multi methods with positional params whose types matter (e.g. for change-cell and print-cell).  I think whatever you want to go with is fine, but it should be a consistent design across the whole API set.

I didn't go with OO::Monitors for concurrent Widget use right off the bat because OO::Monitors doesn't currently support inheritance trees well (and I don't know that it can be used for Roles at all).  I'm pretty sure that's just a limitation of the current OO::Monitors implementation and not something intrinsic to the concept, but that still leaves it as a non-starter until that module rises back to the top of jnthn's work list.

I'm starting to look at some other widget toolkits to see if there are good ideas we can steal (GTK+ for C, ["blessed"](https://github.com/chjj/blessed) for JS, and so forth).  I've only just started, but this has already brought forth the point that concurrency, repaints, and user input all need to be solved as a unified whole, otherwise you get a flakey mess.

(I should note that the fact that blessed is at least 16,000 lines of JS makes me both afraid of the work in front of us, and dying to show that it can be done well in a lot less Perl 6.  ;-) )

**Comment by japhb** [comment]
I've been playing around with a few different ideas trying to figure out how to make composable animations, and I think I'm beginning to see a path forward; check this example to see my current line of thinking:

https://github.com/japhb/Terminal-Print/blob/ui_test/examples/attacks.p6

I've got a larger animation made of small sprite animations, plus a couple variants of particle systems (with doubled vertical resolution, no less).  All three of them are then contained in an overarching animation widget which has been told to capture the root screen grid.

Let me know what you think of the WIP.

**Comment by ab5tract** [comment]
The code looks great, but when I try to run it I get:

````
Invalid attribute name '20'
  in sub color at /Users/john/.rakudobrew/moar-nom/install/share/perl6/site/sources/37E2E5D01D62E5D0E4F3CBBCE0D817264CD0C9E3 (Terminal::ANSIColor) line 45
  in submethod BUILD at /Users/john/code/p6/Terminal-Print/lib/Terminal/Print/Grid.pm6 line 24
  in method change-cell at /Users/john/code/p6/Terminal-Print/lib/Terminal/Print/Grid.pm6 line 161
  in any call_with_capture at gen/moar/Metamodel.nqp line 3888
  in block  at /Users/john/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 line 31
  in block  at /Users/john/.rakudobrew/moar-nom/install/share/perl6/site/sources/B7DF632EBAC65169FAE1AF8BFB774E9775D8BA37 line 25
  in any enter at gen/moar/Metamodel.nqp line 3990
  in block  at examples/attacks.p6 line 211
  in method composite-particles at examples/attacks.p6 line 203
  in method draw-frame at examples/attacks.p6 line 226
  in method do-frame at examples/attacks.p6 line 112
  in block  at examples/attacks.p6 line 83
  in method draw-children at examples/attacks.p6 line 79
  in method do-frame at examples/attacks.p6 line 108
  in block  at examples/attacks.p6 line 333
  in sub MAIN at examples/attacks.p6 line 328
  in block <unit> at examples/attacks.p6 line 312
````

**Comment by japhb** [comment]
Ah!  That's because you've got an old version of Terminal::ANSIColor ... which means you've also been missing out on --color-bits=8 for rpg-ui.  Awww, dang.

Update that module (possibly using --force on the install if it hasn't updated its module version yet), and things should look a lot better.  :-)

**Comment by japhb** [comment]
There are a few more animations in attacks.p6 now.  I'm slowly refactoring, and I think I need to finally introduce screen door transparency as an option for the pixel animations at some point soon, but there's at least some fun eye candy to look at.  :-)

**Comment by japhb** [comment]
And now you can use the --slow-mo=X option to slow down animation time in the attacks.p6 example.  :-)

**Comment by ab5tract** [comment]
So purty! :)

Indeed Tadzik hasn't bumped the `Terminal::ANSIColor` version. Should have tried the force install first, but oh well.

This runs smoothly on my machine. I tried the `animated-widgets.p6` example, which falls down pretty quickly. This is a previous attempt, right?

This is really a major contribution, japhb. Thank you!

**Comment by japhb** [comment]
Glad to hear it's running smoothly!

Yeah, animated-widgets.p6 was specifically testing a particular angle (LOTS of subthreads) and it runs into scaling limitations at the moment.  That's why I went the other direction with attacks.p6.  (Also animated-widgets is intentionally ugly because it was designed to make it easy for me to notice jank and tearing.  Probably time to just junk it.)

/me heads off to the land of nod ...

Oh, but before I do, I keep trying to remember to ask: What is the clock example trying to draw?  I went to fix it a few weeks ago, but wasn't sure what it was actually aiming for.

**Comment by ab5tract** [comment]
OH! How did that one get pushed? `clocks.p6` was supposed to be only a
private shame, haha.

The original idea was to have it advanced one asterisk in a circle, like a
second hand, while the center displayed the time in digits.

Then I came to realize how very little I know about making curves out of
irregularly shaped pixels and....

**Comment by Xliff** [comment]
I've been following this conversation for a while and was interested in
looking at the examples. I went and installed the dependencies and then
went to run the examples from a clone of the repository.

Long story short, I can't get anything in Terminal::Print to run due to a
weird error in OO::Monitors:

 Cannot invoke this object (REPR: Null; VMNull)

This is using rakudo version 2016.11-182-gea28845f9. (Basically, what I was
able to pull off of the git repository about 4 hours ago)

Have any of you seen this error? If not, I will submit this to the
OO::Monitors repo. However, this looks more like a rakudo error than
anything else. I'd advise you to -not- update your OO::Monitors module if
you are actively working on development.

- C/X

**Comment by ab5tract** [comment]
Hey Xliff, I'm sorry it's broken for you. Another user reported the problem in #17 . I hope a minimum case can be developed for `OO::Monitors`. I also hope to one day be able to hack on the module myself, but I haven't gotten around to learning Perl 6 metaprogramming.

Looking at the [OO::Monitors](https://github.com/jnthn/oo-monitors) repo, it looks like jnthn pushed a fix that re-allows precompilation but has not bumped the version. This would explain why I'm not seeing breakage locally, as only a `--force` would cause it to be installed. So I would look first to the reverting the patches from Oct 26.

**Comment by Xliff** [comment]
ab5tract: Thanks. That's a big help!

I reverted to the last commit made on Aug 12th and that seems to do the trick. 

Here's a weird thing though: I can run the rpg-ui.p6 files on my SSH sessions, but when I go to the actual terminal, I get the following error:

> "Type check failed in binding; expected Associative but got Any (Any)"

Might that be due to the fact that VirtualBox guests have screwy termcaps?

Anyways, this looks interesting. I am going to start looking under the hood to  see if I can understand what is going on.

- X/C

**Comment by Xliff** [comment]
BTW - Here is the revert command for OO::Monitors

`git reset --hard b05961683ff7077663894a146cc64326b2487f55`

Just in case anyone else runs into this issue.

**Comment by japhb** [comment]
Xliff:  Certainly a broken termcap would cause problems, since Terminal::Print::Commands uses `tput` to get to the termcap info, and uses that to drive all the escape sequences.

Also, what is the `$TERM` on your VirtualBox guest?

**Comment by japhb** [comment]
ab5tract: You asked for 'line-to', 'curve-to', etc.  Are you wanting to have it draw colored curves for you (perhaps using the double-Y-resolution pixel code from attacks.p6), or plot characters in the right places in a T::P::Grid, or give callbacks for every point in a curve, or ...?  In other words, what's your target API?

Also, any objection to pulling some of the animation and pixel-drawing code out of attacks.p6 and making the classes/roles into standard Terminal::Print::* APIs?

**Comment by Xliff** [comment]
japhb: $TERM = 'linux' from the guest console.

**Comment by japhb** [comment]
Xliff: If you add `linux` to the [valid-terminals list](https://github.com/japhb/Terminal-Print/blob/ui_test/lib/Terminal/Print/Commands.pm6#L26) does it start working?

**Comment by Xliff** [comment]
japhb: Yes, it does, although it looks like the console is set to the wrong
character set.

Nice fix!

- X/C

**Comment by japhb** [comment]
Xliff:  Wrong character set?  I take it it's not set to use Unicode, but something else like [CP 437](https://en.wikipedia.org/wiki/Code_page_437) perhaps?

/me wonders about the best way to support that ...

**Comment by ab5tract** [comment]
@japhb , is it too ambitious to say that I would love to support all of the above? 😀

But maybe `curve-to` deserves its own issue for further discussions. I can definitely see the utility in all of the use cases you mentioned. There might even be others.

I've pushed the latest version of `ui_test` as version 0.90. Also, I thought you might enjoy having direct access to the repo. Considering all the work you've done already, I'd say it's a bit overdue.

**Comment by japhb** [comment]
ab5tract: Nah, not too ambitious.  In fact, instead of callbacks, iterators for generating new points along various lines and curves seems rather 6-y.  :-)

Actually, there are a number of items in this single issue that deserve to be broken out; I'll do that in a bit.

Thanks for merging and pushing the new release, and thank you for giving me direct access!  I'll switch to pushing directly to your repo now.

**Comment by japhb** [comment]
OK, I've taken a number of ideas from this thread and prototype code from `rpg-ui.p6` and `attacks.p6` and created 14 new issues so we can discuss and implement them all separately.

Given that ui_test is merged now, and I think I've captured the open issues we've discussed so far, anyone object to marking this issue closed?

**Comment by ab5tract** [comment]
Alright! Here's to one epic thread down, 15 more to go ;)
