### ISSUE TITLE
Printing entire strings, filling a region, and other commands

### ISSUE THREAD

**Issue by bluebear94** [ab5tract/Terminal-Print#4]
Do you plan to add them or are they too high-level for this library?

**Comment by ab5tract** [comment]
I think it makes sense to add a 'region printing' functionality, specifying a start and end position and optionally supplying a string to print there. Ideally this would also feature some async stuff: maybe a supply that becomes in charge of a specific region which the dev can send updates.

But that's about as high level as we should go, I think. A 'command-line UI' library should be a separate thing.

**Comment by bluebear94** [comment]
Also, I'd like to point out ahead of time that some characters may take two spaces instead of one, and assuming otherwise might screw up displays. Don't know how to detect which characters do, though.

This is also dependent on the terminal emulator used as well as the font. In Atom, ⑨ displays twice as wide as Latin characters, but in the Cygwin terminal (with the same font), it is only as wide as one of them.

There might also be characters that are not exact integer widths.

**Comment by ab5tract** [comment]
Yeah, this has been a known hurdle since the beginning. Please keep in mind that this has been a small project with a user count of one, so not everything is in place yet, I didn't want to solve problems before even encountering them.

Anyway, I think we should be able to get away with just single or double width as defined per the unicode specification. There should be some means of introspecting this from the character object, but I haven't locked it down yet. Atom is probably doing some internal enlargement of some of these characters, which is something that AFAIK we can trust terminal applications _not_ to do.

How I've envisioned the solution:

In the react sub-block that handles storing the characters we check if that character is wide or not. If it is then we make note of it in a second "shadow" grid array. So any printing, wide or not, first checks the shadow grid whether a wide char is technically occupying the coord you want to write to. Note that "occupying" here means only the second half of the wide char. When we print the wide char it will not be truncated but will occupy two spaces as expected. So we can replace the wide char at it's "real" coord, but we cannot print to the space next to it without changing one or both of the characters. We can have it throw an exception when there is a collision between the attempted mutation coordinate and wide character records in the shadow grid.

Unfortunately I don't have any time to hack on this at the moment, but it would be an awesome feature to have.

**Comment by ab5tract** [comment]
Oh, and if there is a character already in the coordinated where the second half of the wide char would go, we need to reset it before we print or the wide char may print incorrectly.

**Comment by bluebear94** [comment]
I think we can check if a space is occupied by the second half of a wide char just by checking if the string stored there is empty, no need to allocate a separate array.

**Comment by ab5tract** [comment]
I'm not sure what you mean. A double-width character will still only be stored in a single cell, so checking the state of the neighboring cell does not tell you enough information.

$grid[0][0] = "あ";
$grid[1][0] eq ' ';  # True
$grid.print-cell(1,0,"A");
$grid.print-cell(0,0);  # should cause a collision and ruin the wide character

But maybe I am missing a detail in your suggestion?

**Comment by bluebear94** [comment]
`$grid.print-cell(1,0,"A");` in your example would check if the cell at (1, 0) is empty before placing the character.

**Comment by ab5tract** [comment]
Right, which is why we need a loomup of some kind. 1,0 is empty regardless
of if 0,0 is wide..

**Comment by bluebear94** [comment]
Ah, misread your comment. I was saying that the second cell occupied by a wide char should be represented by an *empty* string, as opposed to a space.

**Comment by ab5tract** [comment]
Ah! I see what you mean now. Yes, this would definitely work. As an aside, I really don't know how I missed this comment, as I remember checking this thread.

**Comment by ab5tract** [comment]
The latest version provides a `.print-string` method. This can even print multi-line strings. I think this satisfies the original ticket's vision of having strings and regions.

Higher level abstractions can/will be provided by consuming libraries.
