### ISSUE TITLE
Released fork as version 0.96

### ISSUE THREAD

**Issue by JJ** [ab5tract/Terminal-Print#62]
Since there are some other modules like jmp that depend on this module working, and there were several not accepted PRs: #61, for instance, I have [released a fork to the ecosystem](https://github.com/JJ/Terminal-Print) with version 0.96. Since that version takes all 3 PRs that were not accepted, I can't send another PR, but if you decide eventually to accept them, please close this issue and I'll un-release this new version. Refs perl6/ecosystem-unbitrot#526

**Comment by japhb** [comment]
JJ: I haven't heard from ab5tract in a while, but I've got commit rights in this repo, so I've merged those PRs.  I've got some personal diffs I'd like to add anyway, so I can push those here too to prep for a new version.

I've also turned GitHub notifications back on for this repo so that I might notice these in the future.

**Comment by JJ** [comment]
I've un-released the other version; please bump up yours to upgrade it now when the latest pr (#64) has been accepted.
