### ISSUE TITLE
Cell fixed height and width

### ISSUE THREAD

**Issue by hythm7** [ab5tract/Terminal-Print#65]
Is it possible to define fixed width and height for grid cells? for example if I'm printing 4 x 4 grid I expect it to be square-like shape, but when print the grid, the height is always longer than the width due to the difference between  line spacing and letter spacing.

instead of printing this:
```
abcd
efgh
ijkl
mnop
```

print this:
```
a  b  c  d
e  f  g  h
i  j  k  l
m  n  o  p
```

**Comment by japhb** [comment]
Most common fixed-width fonts make the cells about twice as tall as they are wide (that's why the pixel animation examples, which make use of Unicode half-height blocks, don't look badly stretched).  However, many glyphs in non-Latin scripts cannot easily be read when that narrow, so Unicode has the concept of fullwidth glyphs, which are generally drawn over two fixed-width cells.  To make it easier to work with mixed Latin and fullwidth scripts, Unicode defines a block of fullwidth variants for each of the ASCII characters; you can see these used in the rpg-ui example.

So to do what you seem to be looking for, you simply need to use those fullwidth Latin characters instead of the ASCII set, and use a font that actually represents these fullwidth Latin characters correctly.  Sadly that latter bit is surprisingly difficult; a lot of fixed-width fonts don't have proper support for these, so font rendering libraries tend to backfill with variable-width glyphs, and lines of text end up misaligned with each other.

One other possibility is to simply add spaces between all the characters you are outputting, or if placing them one by one, skip drawing the cells in between.  (If you are using non-default character style, you will need to either prefill the grid with properly styled spaces, or stick with adding spaces in between characters in lines of text so that the spaces will get styled properly.)  The downside of using this option as opposed to the fullwidth characters is that the narrow characters will not be centered -- they will appear half a cell to one side of where they "should" be to be properly centered.

Hope this helps, and good luck!

**Comment by hythm7** [comment]
Thank you for the detailed explanation.
