### ISSUE TITLE
vt52 special keys

### ISSUE THREAD

**Issue by kuerbis** [ab5tract/Terminal-Print#81]
Some special keys in `Terminal::Print::DecodedInput` are marked with "VT52 Style". In `Terminal::Print::Commands` `vt52` is not part of the valid terminals. Are these `vt52` special keys there to be prepared for a possible later addition of the `vt52` terminal, or are there `non-vt52` terminals that use these special keys?

**Comment by japhb** [comment]
Primarily that is because:

- It was pretty much free to support the extra sequences, so no strong reason not to
- I didn't know for sure what odd terminal emulators might be sending those escape sequences (some terminals switch formats)
- No one in the community has an actual VT52 to test with, so we can't claim it's a tested terminal

That said, if you actually do happen to have a VT52, I'd be quite happy to hear what you discover.  :-)

**Comment by kuerbis** [comment]
Added `vt52` to the `@valid-terminals` in Terminal::Print::Commands
Called xterm with `xterm -ti vt52 -tn vt52`
Ran the example-script `alphabetic5.p6`

Error-message:
>Tried to use an undefined capability 'civis' of the terminal type 'vt52'.
in sub print-command at ... (Terminal::Print::Commands) line 124
in method initialize-screen at ... (Terminal::Print) line 139
in block <unit> at ./alphabetic5.p6 line 10

This is the output of `infocmp -1 vt52`:

>  cols#80,
    it#8,
    lines#24,
    acsc=+h.k0affggolpnqprrss,
    bel=^G,
    clear=\EH\EJ,
    cr=\r,
    cub1=\ED,
    cud1=\EB,
    cuf1=\EC,
    cup=\EY%p1%' '%+%c%p2%' '%+%c,
    cuu1=\EA,
    ed=\EJ,
    el=\EK,
    home=\EH,
    ht=^I,
    ind=\n,
    kbs=^H,
    kcub1=\ED,
    kcud1=\EB,
    kcuf1=\EC,
    kcuu1=\EA,
    nel=\r\n,
    ri=\EI,
    rmacs=\EG,
    smacs=\EF,
